USE [master]
GO

IF NOT EXISTS (SELECT [name] FROM [sys].[databases] WHERE name = N'ZettaTest')
BEGIN
    CREATE DATABASE [ZettaTest]
END
GO

USE [ZettaTest]
GO

IF NOT EXISTS (SELECT TOP 1 1 FROM [INFORMATION_SCHEMA].[TABLES] WHERE [TABLE_SCHEMA] = 'dbo' AND [TABLE_NAME] = 'Users')
BEGIN
	CREATE TABLE [dbo].[Users] (
		 [Id] INT NOT NULL PRIMARY KEY IDENTITY
		,[UserName] NVARCHAR(150) NOT NULL UNIQUE
		,[Password] NVARCHAR(150) NOT NULL
		,[CreatedAt] DATETIME NOT NULL
		,[LastLogin] DATETIME
	)
END
GO

IF NOT EXISTS (SELECT TOP 1 1 FROM [INFORMATION_SCHEMA].[TABLES] WHERE [TABLE_SCHEMA] = 'dbo' AND [TABLE_NAME] = 'TimeValues')
BEGIN
	CREATE TABLE [dbo].[TimeValues] (
		 [Id] INT NOT NULL PRIMARY KEY IDENTITY
		,[Date] DATETIME NOT NULL
		,[Value] INT NOT NULL
		,[CreatedBy] INT NOT NULL FOREIGN KEY REFERENCES [dbo].[Users]([Id])
		,[CreatedAt] DATETIME NOT NULL
	)
END
GO